### ISSUE TITLE
What makes this specific to a Lumen / Laravel project?

### ISSUE THREAD

**Issue by digitaloutback** [spiritix/lumen-aws-gitlab-continuous-deployment#1]

**Comment by spiritix** [comment]
For example the use of .env files, the calls to the Artisan database migrations, or at a low level simply the dependencies which are specifically being installed for Lumen. That being said, it should be rather easy to adopt this boilerplate for other frameworks and projects.

The idea of this repository is mainly to give people a good starting point when setting up a CD pipeline to AWS EB using Gitlab, which took me quite some time to figure out.
